import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fixture,mechanismXml} from './report_quality_fixture.mjs';
import {checkReport,checkFile,digest} from '../scripts/report_quality.mjs';
import {deliverWithBoundedRetry} from '../scripts/report_delivery_retry.mjs';
const check=(mutate=()=>{},type='business')=>{const a=fixture(type);mutate(a);return checkReport(a);};
const has=(r,id)=>r.issues.some(i=>i.rule_id===id&&!i.waived);
for(const type of ['business','retention','research','mechanism'])test(`profile ${type} passes`,()=>assert.equal(check(()=>{},type).errors,0));
test('XML mechanism is text-only, not falsely calculation certified',()=>{const r=checkReport(mechanismXml,{format:'xml'});assert.equal(r.errors,0);assert.equal(r.coverage.declared_calculations,'not_declared');assert.equal(r.coverage.lark_readback,'not_checked');});
test('mechanism plan can use overall-plan opening without duplicate summary',()=>assert.equal(checkReport(mechanismXml.replace('先看结论','总体方案'),{format:'xml'}).errors,0));
test('Markdown warning includes a line location and ignores fenced headings',()=>{const r=checkReport('# 模拟报告\n\n## 执行摘要\n\n需求合同说明。\n\n```\n## Executive Summary\n```',{format:'markdown'});assert.equal(r.errors,0);assert.ok(r.issues.some(x=>x.rule_id==='W003'&&x.location==='markdown:line:5'));});
test('malformed JSON/object rejected',()=>assert.ok(has(checkReport(null),'R001')));
test('null components and dataset rows are reported rather than thrown',()=>{for(const mutate of [a=>a.manifest.charts=[null],a=>a.manifest.blocks=[null],a=>a.snapshot.datasets.d=[null]])assert.ok(has(check(mutate),'R001'));});
test('invalid metric bounds and references rejected',()=>{assert.ok(has(check(a=>{a.manifest.reportContract.metrics[0].min='bad';}),'R014'));assert.ok(has(check(a=>{a.manifest.reportContract.metrics[0].field='missing';}),'R004'));});
test('XML external entities rejected',()=>assert.ok(has(checkReport('<!DOCTYPE x><title>x</title>',{format:'xml'}),'R001')));
test('missing title rejected',()=>assert.ok(has(check(a=>{a.manifest.title='';}),'R002')));
test('title placeholder is not a deliverable title',()=>assert.ok(has(check(a=>{a.manifest.title='{{报告标题}}';a.manifest.blocks[0].body='# {{报告标题}}';}),'R002')));
test('English default heading rejected',()=>assert.ok(has(check(a=>{a.manifest.blocks[1].body='## Executive Summary\n\n**模拟说明。** 示例只有结构用途。';}),'R003')));
test('explicit English task allowed',()=>{const r=check(a=>{a.manifest.reportContract.language='en';a.manifest.blocks[1].body='## Executive Summary\n\n**Synthetic data.** For template testing only.\n\n**Same denominator.** No business claim.';});assert.equal(r.errors,0);});
test('RTP and product names preserved',()=>assert.equal(check(a=>{a.manifest.blocks.push({id:'r',type:'markdown',body:'## RTP与APP/H5\n\n保留必要指标名；结算回报率以已确认的分子和分母计算。'});}).errors,0));
test('missing chart reference rejected',()=>assert.ok(has(check(a=>{a.manifest.blocks[3].chartId='missing';}),'R004')));
test('missing dataset rejected',()=>assert.ok(has(check(a=>{a.manifest.charts[0].dataset='missing';}),'R004')));
test('missing field rejected',()=>assert.ok(has(check(a=>{a.manifest.charts[0].encodings.y.field='absent';}),'R004')));
test('explicit count units in legacy charts are recognized',()=>{for(const label of ['数据记录项数','品牌数','人口（百万人）'])assert.equal(check(a=>{delete a.manifest.reportContract;a.manifest.charts[0].encodings.y={field:'n',label};a.manifest.sources[0].query.metric_definitions=[];}).errors,0);});
test('missing sort warns while a nonexistent sort column blocks',()=>{let r=check(a=>{delete a.manifest.tables[0].defaultSort;});assert.equal(r.errors,0);assert.ok(has(r,'W011'));r=check(a=>{a.manifest.tables[0].defaultSort.field='missing';});assert.ok(has(r,'R004'));});
test('missing source rejected',()=>assert.ok(has(check(a=>{a.manifest.sources=[];}),'R008')));
test('new context missing blocks',()=>assert.ok(has(check(a=>{delete a.manifest.reportContract.population;}),'R005')));
test('unfilled context placeholder is rejected',()=>assert.ok(has(check(a=>{a.manifest.reportContract.period='{{统计窗口}}';}),'R005')));
test('old format is explicitly limited, not rewritten',()=>{const a=fixture();delete a.manifest.reportContract;const before=JSON.stringify(a);const r=checkReport(a);assert.equal(r.errors,0);assert.ok(has(r,'W001'));assert.equal(JSON.stringify(a),before);});
test('different new-user definitions both permitted',()=>{for(const p of ['注册当天为新用户','行为日账号龄0—29天为新用户'])assert.equal(check(a=>{a.manifest.reportContract.population=p;}).errors,0);});
test('percentage point scale with percent formatting rejected',()=>assert.ok(has(check(a=>{a.manifest.reportContract.metrics[0].scale='percent_points';},'retention'),'R007')));
test('RTP over 100% is not a generic error',()=>{const r=check(a=>{a.snapshot.datasets.d[0]={group:'模拟RTP',n:120,d:100,rate:1.2,rate_pct:120,percent_base:100};delete a.manifest.reportContract.metrics[0].max;},'retention');assert.equal(r.errors,0);});
test('declared penetration upper bound enforced',()=>assert.ok(has(check(a=>{a.snapshot.datasets.d[0].rate=1.2;},'retention'),'R007')));
test('zero denominator requires null, not zero',()=>assert.ok(has(check(a=>{a.snapshot.datasets.d[0]={group:'空分母',n:0,d:0,rate:0};}),'R009')));
test('zero denominator N/A accepted',()=>assert.equal(check(a=>{a.snapshot.datasets.d[0]={group:'未达到观察天数',n:0,d:0,rate:null};}).errors,0));
test('ratio denominator is required',()=>assert.ok(has(check(a=>{delete a.manifest.reportContract.metrics[0].denominator;},'retention'),'R006')));
test('pp and relative percentage are distinct',()=>{const r=check(a=>{a.snapshot.datasets.d[0].before=.5;a.snapshot.datasets.d[0].after=.4;a.snapshot.datasets.d[0].change=-.1;a.manifest.reportContract.assertions=[{kind:'difference_pp',dataset:'d',where:{group:'样例1'},before:'before',after:'after',actual:'change'}];});assert.ok(has(r,'R009'));});
test('correct pp and relative change pass',()=>assert.equal(check(a=>{Object.assign(a.snapshot.datasets.d[0],{before:.5,after:.4,pp:-10,rel:-.2});a.manifest.reportContract.assertions=[{kind:'difference_pp',dataset:'d',where:{group:'样例1'},before:'before',after:'after',actual:'pp'},{kind:'relative_change',dataset:'d',where:{group:'样例1'},before:'before',after:'after',actual:'rel'}];}).errors,0));
test('cross-table mismatch located',()=>assert.ok(has(check(a=>{a.snapshot.datasets.other=[{group:'样例1',n:999}];a.manifest.reportContract.assertions=[{kind:'equal',left:{dataset:'d',field:'n',where:{group:'样例1'}},right:{dataset:'other',field:'n',where:{group:'样例1'}}}];}),'R009')));
test('confirmed parameter cannot also be open',()=>assert.ok(has(check(a=>{a.manifest.reportContract.decisions={new_user:{status:'confirmed',value:'注册当日'}};a.manifest.reportContract.openQuestions=[{parameter:'new_user'}];}),'R012')));
test('legacy natural-language conflict is a review warning',()=>{const r=check(a=>{a.manifest.blocks.push({id:'conflict',type:'markdown',body:'统计日期当天注册为新用户。\n\n新用户采用注册当日还是注册后N天？'});});assert.ok(has(r,'W011'));assert.equal(r.errors,0);});
test('necessary negations preserved',()=>{const r=check(a=>{a.manifest.blocks.push({id:'safe',type:'markdown',body:'不能把未达到观察天数的数据当作零；不能混用不可比人群；不得上传凭据和个人信息。'});});assert.equal(r.errors,0);assert.ok(!has(r,'W006'));});
test('style warnings do not block',()=>{const r=check(a=>{a.manifest.blocks.push({id:'long',type:'markdown',body:'需求合同需要进一步优化。'.repeat(30)});});assert.equal(r.errors,0);assert.ok(has(r,'W002'));assert.ok(has(r,'W003'));});
test('chart must have adjacent interpretation',()=>assert.ok(has(check(a=>{a.manifest.blocks[2].body='## 只有标题';}),'R015')));
test('scatter labels and line key points require review',()=>{const r=check(a=>{a.manifest.charts[0].type='scatter';});assert.ok(has(r,'W009'));});
test('raw personal rows are blocked without echoing values',()=>{const r=check(a=>{a.snapshot.datasets.d[0].user_id='private-value-not-to-echo';});assert.ok(has(r,'R011'));assert.ok(!JSON.stringify(r).includes('private-value-not-to-echo'));});
test('quoted JSON credential-like values are blocked without echoing them',()=>{const r=check(a=>{a.extra={api_key:'sk-synthetic-placeholder-not-a-real-key'};});assert.ok(has(r,'R011'));assert.ok(!JSON.stringify(r).includes('sk-synthetic'));});
test('invalid assertion cannot silently pass',()=>assert.ok(has(check(a=>{a.manifest.reportContract.assertions=[{kind:'invented'}];}),'R014')));
test('empty assertion selection cannot silently pass',()=>assert.ok(has(check(a=>{a.manifest.reportContract.assertions[0].where={group:'not present'};}),'R014')));
test('render failure blocks; structural-only remains visible',()=>{assert.ok(has(checkReport(fixture(),{verification:{ok:false}}),'R013'));const r=checkReport(fixture(),{verification:{ok:true,stages:{verification:'structural_only'}}});assert.ok(has(r,'W010'));assert.equal(r.coverage.visual,'structural_only');});
test('Lark false checks block despite a positive status',()=>{const r=checkReport(fixture(),{verification:{status:'readback_verified',document_id:'synthetic',revision:1,checks:{images:false}}});assert.ok(has(r,'R013'));assert.equal(r.coverage.lark_readback,'not_checked');});
test('exceptions require hash-bound real approval record',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'waje-report-exception-'));
 try{const a=fixture();a.manifest.blocks[3].chartId='missing';let r=checkReport(a,{exceptions:[{rule_id:'R004',location:'manifest.blocks[3]',reason:'test'}]});assert.ok(has(r,'R010'));
 const b=fixture();b.manifest.reportContract.metrics=[];b.manifest.charts[0].encodings.y={field:'n',label:'量'};b.manifest.sources[0].query.metric_definitions=[];
 fs.writeFileSync(path.join(dir,'approval.md'),'合成测试批准记录，不是实际业务授权。');
 const ex={report_sha256:digest(JSON.stringify(b)),rule_id:'R006',location:'chart.c.unit',reason:'仅测试精确范围批准引用',approved_by:'test-fixture',approval_reference:{path:'approval.md',sha256:digest(fs.readFileSync(path.join(dir,'approval.md')))}};
 r=checkReport(b,{root:dir,exceptions:[ex]});assert.equal(r.errors,0);assert.equal(r.exceptions_applied.length,1);
 b.snapshot.datasets.d[0].n=999;r=checkReport(b,{root:dir,exceptions:[ex]});assert.ok(has(r,'R010'));
 }finally{fs.rmSync(dir,{recursive:true});}
});
test('invalid exception list is rejected',()=>assert.ok(has(checkReport(fixture(),{exceptions:{}}),'R010')));
test('only transient local probe failure retries once with full record',async()=>{let n=0;const r=await deliverWithBoundedRetry(async()=>++n===1?{ok:false,stage:'verification',code:'reader_timeout'}:{ok:true,stages:{verification:'passed'}});assert.equal(n,2);assert.equal(r.ok,true);assert.equal(r.attempts[0].ok,false);});
test('two transient failures stop and data defects never retry',async()=>{let n=0;let r=await deliverWithBoundedRetry(async()=>{n++;return {ok:false,stage:'verification',code:'reader_timeout'};});assert.equal(n,2);assert.equal(r.ok,false);n=0;r=await deliverWithBoundedRetry(async()=>{n++;return {ok:false,stage:'verification',code:'overflow'};});assert.equal(n,1);assert.equal(r.ok,false);});
test('source mutation blocks any second attempt',async()=>{let n=0;const r=await deliverWithBoundedRetry(async()=>{n++;return {ok:false,stage:'verification',code:'reader_timeout'};},()=>n===0);assert.equal(n,1);assert.equal(r.code,'input_changed');});
test('check-only never imports renderer or writes report',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'waje-report-check-'));
 try{const f=path.join(dir,'fixture.json'),out=path.join(dir,'output.html');fs.writeFileSync(f,JSON.stringify(fixture()));const before=fs.readFileSync(f);
 const r=spawnSync(process.execPath,['scripts/deliver_readable_report.mjs','--input',f,'--check-only','--output',out],{encoding:'utf8',env:{...process.env,WAJE_ANALYTICS_PLUGIN_ROOT:'/nonexistent-plugin-for-test'}});
 assert.equal(r.status,0,r.stderr);assert.equal(fs.existsSync(out),false);assert.deepEqual(fs.readFileSync(f),before);assert.equal(JSON.parse(r.stdout).network_calls,0);
 const bad=fixture();bad.manifest.sources=[];fs.writeFileSync(f,JSON.stringify(bad));const block=spawnSync(process.execPath,['scripts/deliver_readable_report.mjs','--input',f,'--output',out],{encoding:'utf8',env:{...process.env,WAJE_ANALYTICS_PLUGIN_ROOT:'/nonexistent-plugin-for-test'}});
 assert.equal(block.status,1);assert.equal(fs.existsSync(out),false);assert.equal(JSON.parse(block.stdout).stage,'report_quality');
 }finally{fs.rmSync(dir,{recursive:true});}
});
