-- Read-only metadata inventory. Returns table names and field paths only; no table rows.
SELECT 'GE_90006' AS dataset_id, t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.GE_90006.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.GE_90006.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'ares_hfyl', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.ares_hfyl.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.ares_hfyl.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'ares_hfyl_test', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.ares_hfyl_test.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.ares_hfyl_test.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'bigdata', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.bigdata.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.bigdata.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'origin_hfyl', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.origin_hfyl.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.origin_hfyl.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'pubwaje', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.pubwaje.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.pubwaje.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'track_hfyl', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.track_hfyl.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.track_hfyl.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'waje_ng_firebase_h5', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.waje_ng_firebase_h5.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.waje_ng_firebase_h5.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'waje_ng_firebase_ios', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.waje_ng_firebase_ios.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.waje_ng_firebase_ios.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'waje_ng_firebase_ios_crashlytics', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.waje_ng_firebase_ios_crashlytics.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.waje_ng_firebase_ios_crashlytics.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'waje_ng_firebase_ios_messaging', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.waje_ng_firebase_ios_messaging.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.waje_ng_firebase_ios_messaging.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
UNION ALL SELECT 'waje_ng_firebase_ios_performance', t.table_name, t.table_type, t.creation_time, c.field_path, c.data_type, c.description FROM `wajenigeria.waje_ng_firebase_ios_performance.INFORMATION_SCHEMA.TABLES` AS t LEFT JOIN `wajenigeria.waje_ng_firebase_ios_performance.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS` AS c USING (table_name)
ORDER BY dataset_id, table_name, field_path;
