#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent;D=json.loads((ROOT/'player-return-2026-09-10.json').read_text());rows=[]
for r in D['daily']['gross_return_ranking'][:5]:rows.append({'scope':'9月10日总回收额','game':r['game'],'complete_bet':r['complete_bet'],'platform_actual_profit':r['platform_actual_profit'],'player_gross_return':r['player_gross_return'],'share':r['gross_return_share'],'actual_rtp':r['actual_rtp']})
for r in D['daily']['net_gain_ranking']:rows.append({'scope':'9月10日玩家净赢','game':r['game'],'complete_bet':r['complete_bet'],'platform_actual_profit':r['platform_actual_profit'],'player_gross_return':r['player_net_gain'],'share':None,'actual_rtp':r['actual_rtp']})
for r in D['weekly_net_gain_ranking']:rows.append({'scope':'9月4—10日玩家净赢','game':r['game'],'complete_bet':r['complete_bet'],'platform_actual_profit':r['platform_actual_profit'],'player_gross_return':r['player_net_gain'],'share':None,'actual_rtp':r['actual_rtp']})
payload={'schemaVersion':1,'items':[{'id':'game-player-return','title':'9月10日玩家回收额与过去7天净赢贡献','queries':[{'id':'lifecycle-game-summary','reportingPeriod':'Sep 10, 2026 and Sep 4–10, 2026','source':{'label':'GM Lifecycle Pool v2 (Joint)','files':['新包生命周期V2 - 含联运2026.9.4-9.10_Joint修正版.xlsx'],'filters':['Business date: Sep 10, 2026','Weekly window: Sep 4–10, 2026','Game-level aggregate rows only'],'executedAt':'2026-09-11T10:54:47+08:00','caveats':['Gross player return includes returned stake and is not net player income.','Game settlement and withdrawal are not linked in the approved aggregate layer, so no game is attributed as the cause of a specific withdrawal.'],'metricDefinitions':[{'label':'Player gross return','definition':'Complete bet amount minus complete actual platform profit; includes returned stake.','formula':'player gross return = complete bet - complete actual platform profit','componentIds':['game-player-return']},{'label':'Player net gain','definition':'The absolute value of negative complete actual platform profit after aggregating a game; positive platform profit produces zero player net gain at that game-total grain.','formula':'player net gain = max(-complete actual platform profit, 0)','componentIds':['game-player-return']}],'evidenceFlow':[{'kind':'validation','title':'Source validation','body':'Sep 10 contains 31 game rows; duplicate keys are absent and the lifecycle four-table reconciliation passed.'}]},'rows':rows,'columns':[{'field':'scope','label':'Scope'},{'field':'game','label':'Game'},{'field':'complete_bet','label':'Complete bet'},{'field':'platform_actual_profit','label':'Platform actual profit'},{'field':'player_gross_return','label':'Player return or net gain'},{'field':'share','label':'Share of Sep 10 gross return'},{'field':'actual_rtp','label':'Actual RTP'}],'methods':[{'language':'calculation','code':'player gross return = complete bet - complete actual platform profit\nplayer net gain = max(-complete actual platform profit, 0)'}],'preview':{'kind':'aggregate','note':'Game-level aggregates only; no player, wallet, order, or withdrawal records.','totalRows':len(rows)}}]}]}
(ROOT/'player-return-2026-09-10-sources.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2));print(json.dumps({'rows':len(rows)}))
