#!/usr/bin/env python3
import json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parent;D=json.loads((ROOT/'tc-2026-09-10-diagnostic.json').read_text());ledger=json.loads((ROOT/'query-ledger.json').read_text())['entries'];ended={e['sql']:datetime.fromisoformat(e['ended']).isoformat()for e in ledger}
table={'name':'wajenigeria.origin_hfyl.view_event_server'}
def source(sql,label,definitions,caveats=[]):
    return {'label':label,'tables':[table],'sql':(ROOT/'queries'/sql).read_text(),'filters':['App ID: 90006','Business dates: Sep 4–10, 2026','Successful server recharge and withdrawal events only'],'caveats':caveats,'executedAt':ended[sql],'metricDefinitions':definitions}
h=D['headline'];f=D['frequency_and_value'];c=D['concentration']
payload={'schemaVersion':1,'items':[
 {'id':'tc-accounting-driver','title':'9月10日TC升至83.40%的直接构成','queries':[
  {'id':'tc-daily','reportingPeriod':'Sep 10, 2026 versus Sep 4–9 daily average','source':source('01_tc_daily_channel.sql','Waje server money events',[{'label':'TC','definition':'Successful withdrawal amount divided by successful cash recharge amount for the same Africa/Lagos business day.','componentIds':['tc-accounting-driver'],'formula':'TC = withdrawal / recharge','sourceLineage':[{'tables':['wajenigeria.origin_hfyl.view_event_server']}]},{'label':'TC accounting decomposition','definition':'The withdrawal increase is applied at Sep 10 recharge, then the larger recharge denominator is applied; the two effects add exactly to the TC change.','componentIds':['tc-accounting-driver']}],['Channel attribution is excluded because the available same-day profile join misses most historical users.']),'rows':[{'period':'Sep 4–9 daily average','recharge':h['recharge_base_daily_average'],'withdraw':h['withdraw_base_daily_average'],'tc':h['tc_base_daily_average']},{'period':'Sep 10','recharge':h['recharge_target'],'withdraw':h['withdraw_target'],'tc':h['tc_target']}],'columns':[{'field':'period','label':'Period'},{'field':'recharge','label':'Successful recharge (source units)'},{'field':'withdraw','label':'Successful withdrawal (source units)'},{'field':'tc','label':'TC'}],'methods':[{'language':'calculation','code':f"Withdrawal effect = ({h['withdraw_target']:.2f} - {h['withdraw_base_daily_average']:.2f}) / {h['recharge_target']:.2f} = {h['withdraw_numerator_effect_pp']:.4f} pp\nRecharge denominator effect = {h['recharge_denominator_effect_pp']:.4f} pp\nNet TC change = {h['change_pp']:.4f} pp"}],'preview':{'kind':'aggregate','note':'Two aggregate comparison rows; no transaction-level data.','totalRows':2}}
  ,{'id':'event-client','reportingPeriod':'Sep 10, 2026 versus Sep 4–9','source':source('08_tc_event_client.sql','Waje event-client audit',[{'label':'Event client availability','definition':'The server money-event client_type field was tested before any platform attribution.','componentIds':['tc-accounting-driver']}],['All successful server money events in the compared period are classified as unknown client; no platform conclusion is drawn.']),'rows':D['data_quality']['event_client_rows'],'columns':[{'field':'metric','label':'Metric'},{'field':'period','label':'Period'},{'field':'event_client','label':'Event client'},{'field':'amount','label':'Amount'}],'preview':{'kind':'aggregate','note':'Aggregate availability check; all rows are unknown client.','totalRows':4}}
 ]},
 {'id':'withdrawal-value-concentration','title':'提现增量主要来自更高金额而非订单数量暴增','queries':[
  {'id':'daily-users','reportingPeriod':'Sep 10, 2026 versus Sep 4–9 daily average','source':source('07_tc_daily_users.sql','Waje daily money-user aggregates',[{'label':'Daily withdrawers','definition':'Approximate distinct users with a successful withdrawal in each Africa/Lagos business day.','componentIds':['withdrawal-value-concentration']},{'label':'Withdrawal amount per user','definition':'Successful withdrawal amount divided by approximate distinct daily withdrawers.','componentIds':['withdrawal-value-concentration']}]),'rows':[{'measure':'Withdraw users change','value':f['withdraw_users_change_pct']},{'measure':'Withdraw transactions change','value':f['withdraw_transactions_change_pct']},{'measure':'Withdrawal amount per user change','value':f['withdraw_amount_per_user_change_pct']},{'measure':'Transactions per withdrawer change','value':f['withdraw_transactions_per_user_change_pct']}],'columns':[{'field':'measure','label':'Measure'},{'field':'value','label':'Change'}],'preview':{'kind':'aggregate','note':'Daily aggregate comparisons; distinct-user counts are approximate.','totalRows':4}},
  {'id':'distribution','reportingPeriod':'Sep 10, 2026 versus Sep 4–9 pooled transactions','source':source('04_tc_distribution.sql','Waje transaction distribution aggregates',[{'label':'Top 1% withdrawal share','definition':'Share of successful withdrawal amount from the largest approximately 1% of successful withdrawal transactions within each compared period.','componentIds':['withdrawal-value-concentration']},{'label':'Amount-band contribution','definition':'Sep 10 amount in each transaction band minus the Sep 4–9 daily average for that band.','componentIds':['withdrawal-value-concentration']}]),'rows':[{'measure':'Withdraw P99','baseline':c['withdraw_p99_base'],'sep10':c['withdraw_p99_target']},{'measure':'Top 1% withdrawal share','baseline':c['withdraw_top_1pct_share_base'],'sep10':c['withdraw_top_1pct_share_target']},{'measure':'20k+ share of withdrawal increase','baseline':None,'sep10':c['withdraw_20k_plus_share_of_increment']}],'columns':[{'field':'measure','label':'Measure'},{'field':'baseline','label':'Sep 4–9'},{'field':'sep10','label':'Sep 10'}],'preview':{'kind':'aggregate','note':'Distribution statistics and amount-band contributions only.','totalRows':3}}
 ]},
 {'id':'withdrawal-time-pattern','title':'提现增量分布在多个时段，15:00—17:59贡献最大','queries':[
  {'id':'time-format','reportingPeriod':'Sep 10, 2026','source':source('05_time_format.sql','Waje server timestamp audit',[{'label':'Business-hour conversion','definition':'The 13-digit server event timestamp is converted from epoch milliseconds to Africa/Lagos time.','componentIds':['withdrawal-time-pattern']}]),'rows':[{'time_format':'13-digit epoch milliseconds','business_day_start':'00:00 Africa/Lagos','corresponding_utc':'23:00 previous UTC day'}],'columns':[{'field':'time_format','label':'Timestamp format'},{'field':'business_day_start','label':'Business-day start'},{'field':'corresponding_utc','label':'UTC equivalent'}],'preview':{'kind':'aggregate','note':'Timestamp-format audit; no event timestamps returned.','totalRows':1}},
  {'id':'three-hour','reportingPeriod':'Sep 10, 2026 versus Sep 4–9 daily average','source':source('06_tc_3hour.sql','Waje three-hour money aggregates',[{'label':'Three-hour withdrawal increment','definition':'Successful withdrawal amount in a three-hour Africa/Lagos band on Sep 10 minus the Sep 4–9 daily average for the same band.','componentIds':['withdrawal-time-pattern']}]),'rows':sorted(D['three_hour'],key=lambda r:r['withdraw_increment'],reverse=True)[:4],'columns':[{'field':'time_band','label':'Africa/Lagos time band'},{'field':'withdraw_target','label':'Sep 10 withdrawal'},{'field':'withdraw_base_daily_avg','label':'Baseline daily average'},{'field':'withdraw_increment','label':'Increment'}],'preview':{'kind':'aggregate','note':'Top four three-hour bands by withdrawal increment.','totalRows':8}}
 ]}
]}
(ROOT/'tc-2026-09-10-sources.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2));print(json.dumps({'items':len(payload['items']),'queries':sum(len(i['queries'])for i in payload['items'])}))
