#!/usr/bin/env python3
import json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parent;Q=json.loads((ROOT/'queries/01_tc_daily_channel.result.json').read_text());rows=[r for r in Q['rows']if r['row_type']=='daily'];prev=[r for r in rows if'2026-09-03'<=r['biz_date']<='2026-09-09'];target=next(r for r in rows if r['biz_date']=='2026-09-10')
summary=[{'period':'Sep 3–9 total','days':7,'recharge':sum(r['recharge']for r in prev),'withdraw':sum(r['withdraw']for r in prev),'tc':sum(r['withdraw']for r in prev)/sum(r['recharge']for r in prev),'recharge_orders':sum(r['recharge_orders']for r in prev),'withdraw_orders':sum(r['withdraw_orders']for r in prev)},{'period':'Sep 3–9 daily average','days':1,'recharge':sum(r['recharge']for r in prev)/7,'withdraw':sum(r['withdraw']for r in prev)/7,'tc':sum(r['withdraw']for r in prev)/sum(r['recharge']for r in prev),'recharge_orders':sum(r['recharge_orders']for r in prev)/7,'withdraw_orders':sum(r['withdraw_orders']for r in prev)/7},{'period':'Sep 10','days':1,'recharge':target['recharge'],'withdraw':target['withdraw'],'tc':target['tc_rate'],'recharge_orders':target['recharge_orders'],'withdraw_orders':target['withdraw_orders']}]
ledger=json.loads((ROOT/'query-ledger.json').read_text())['entries'];ended=datetime.fromisoformat(next(e['ended']for e in ledger if e['sql']=='01_tc_daily_channel.sql')).isoformat()
payload={'schemaVersion':1,'items':[{'id':'tc-sep10-prior-seven','title':'9月10日资金与此前7日比较','queries':[{'id':'tc-daily','reportingPeriod':'Sep 3–10, 2026','source':{'label':'Waje server money events','tables':[{'name':'wajenigeria.origin_hfyl.view_event_server'}],'sql':(ROOT/'queries/01_tc_daily_channel.sql').read_text(),'filters':['App ID: 90006','Business dates used here: Sep 3–10, 2026','Successful server recharge and withdrawal events only','Business timezone: Africa/Lagos'],'executedAt':ended,'caveats':['Sep 3–9 totals are divided by seven for a like-for-like daily comparison with Sep 10.'],'metricDefinitions':[{'label':'TC','definition':'Successful withdrawal amount divided by successful cash recharge amount for the same business-day scope.','formula':'TC = withdrawal / recharge','componentIds':['tc-sep10-prior-seven']}]},'rows':summary,'columns':[{'field':'period','label':'Period'},{'field':'recharge','label':'Successful recharge'},{'field':'withdraw','label':'Successful withdrawal'},{'field':'tc','label':'TC'},{'field':'recharge_orders','label':'Recharge orders'},{'field':'withdraw_orders','label':'Withdrawal orders'}],'methods':[{'language':'calculation','code':'prior-seven daily average = sum(Sep 3 through Sep 9) / 7\nchange = Sep 10 / prior-seven daily average - 1'}],'preview':{'kind':'aggregate','note':'Aggregate daily comparison only; no user or transaction rows.','totalRows':3}}]}]}
(ROOT/'tc-0910-vs-prior7-sources.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2));print(json.dumps({'rows':summary},ensure_ascii=False))
