#!/usr/bin/env python3
import glob,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parent;D=json.loads((ROOT/'tada-tc-2026-09-10-vs-prior7.json').read_text());ledger=json.loads((ROOT/'tada-query-ledger.json').read_text())['entries'];by={e['sql']:e for e in ledger};queries=[]
for path in sorted(glob.glob(str(ROOT/'queries/12?_tada_tc_*.sql'))):
    p=Path(path);result=json.loads(p.with_suffix('.result.json').read_text());entry=by[p.name]
    queries.append({'id':p.stem.replace('_','-'),'reportingPeriod':f"{result['dry']['scope']['start']} through {result['dry']['scope']['end']}",'source':{'label':'Google Cloud BigQuery API — Waje server events','tables':[{'name':'wajenigeria.origin_hfyl.view_event_server'}],'sql':p.read_text(),'filters':['App ID: 90006','Tada play ID: 9150001–9159999','Waje mode ID: 11','Positive-stake GAMEEND users only','Same-business-day successful recharge and withdrawal','Business timezone: Africa/Lagos'],'executedAt':datetime.fromisoformat(entry['ended']).isoformat(),'caveats':['Tada cohort wallet amounts include all same-day money activity of Tada bettors and are not direct game-to-transaction attribution.'],'metricDefinitions':[{'label':'Tada participant TC','definition':'Same-day successful withdrawal amount divided by same-day successful recharge amount among users who placed a positive Tada stake that business day.','formula':'Tada participant TC = same-day withdrawal / same-day recharge','componentIds':['tada-participant-tc']}]},'rows':result['rows'],'columns':[{'field':'biz_date','label':'Business date'},{'field':'tada_bettors','label':'Tada bettors'},{'field':'recharge_users','label':'Recharge users'},{'field':'withdraw_users','label':'Withdrawal users'},{'field':'recharge','label':'Successful recharge'},{'field':'withdraw','label':'Successful withdrawal'},{'field':'tc_rate','label':'TC'}],'preview':{'kind':'aggregate','note':'Daily aggregate Tada-participant wallet metrics only; no identifiers.','totalRows':len(result['rows'])}})
payload={'schemaVersion':1,'items':[{'id':'tada-participant-tc','title':'9月10日Tada参与人群充提与前7日比较','queries':queries}]}
(ROOT/'tada-tc-2026-09-10-sources.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2));print(json.dumps({'queries':len(queries),'rows':sum(len(q['rows'])for q in queries)}))
