#!/usr/bin/env python3
import glob,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parent;rows=[]
for path in sorted(glob.glob(str(ROOT/'queries/12?_tada_tc_*.result.json'))):rows+=json.loads(Path(path).read_text())['rows']
rows.sort(key=lambda r:r['biz_date']);assert len(rows)==8 and all(r['duplicate_recharge_rows']==0 and r['duplicate_withdraw_rows']==0 for r in rows)
target=rows[-1];previous=rows[:-1];avg=lambda rs,k:sum(r[k]for r in rs)/len(rs)
summary={'prior7_start':'2026-09-03','prior7_end':'2026-09-09','prior7_recharge_total':sum(r['recharge']for r in previous),'prior7_withdraw_total':sum(r['withdraw']for r in previous),'prior7_recharge_daily_average':avg(previous,'recharge'),'prior7_withdraw_daily_average':avg(previous,'withdraw'),'prior7_tc_weighted':sum(r['withdraw']for r in previous)/sum(r['recharge']for r in previous),'target':target,'recharge_change_vs_daily_average':target['recharge']/avg(previous,'recharge')-1,'withdraw_change_vs_daily_average':target['withdraw']/avg(previous,'withdraw')-1,'tc_change_pp':(target['tc_rate']-sum(r['withdraw']for r in previous)/sum(r['recharge']for r in previous))*100,'bettors_change':target['tada_bettors']/avg(previous,'tada_bettors')-1,'recharge_users_change':target['recharge_users']/avg(previous,'recharge_users')-1,'withdraw_users_change':target['withdraw_users']/avg(previous,'withdraw_users')-1,'recharge_amount_per_user_change':(target['recharge']/target['recharge_users'])/(sum(r['recharge']/r['recharge_users']for r in previous)/7)-1,'withdraw_amount_per_user_change':(target['withdraw']/target['withdraw_users'])/(sum(r['withdraw']/r['withdraw_users']for r in previous)/7)-1,'recharge_amount_per_order_change':(target['recharge']/target['recharge_orders'])/(sum(r['recharge']/r['recharge_orders']for r in previous)/7)-1,'withdraw_amount_per_order_change':(target['withdraw']/target['withdraw_orders'])/(sum(r['withdraw']/r['withdraw_orders']for r in previous)/7)-1}
overall=[r for r in json.loads((ROOT/'queries/01_tc_daily_channel.result.json').read_text())['rows']if r['row_type']=='daily'and'2026-09-03'<=r['biz_date']<='2026-09-10'];oprev=overall[:-1];otarget=overall[-1]
summary.update({'tada_share_of_target_recharge':target['recharge']/otarget['recharge'],'tada_share_of_target_withdraw':target['withdraw']/otarget['withdraw'],'tada_share_of_total_withdraw_increment':(target['withdraw']-avg(previous,'withdraw'))/(otarget['withdraw']-avg(oprev,'withdraw')),'tada_share_of_total_recharge_increment':(target['recharge']-avg(previous,'recharge'))/(otarget['recharge']-avg(oprev,'recharge'))})
result={'generated_at':datetime.now(timezone.utc).isoformat(),'status':'validated_aggregate_only','definition':'每日参与Tada并产生正向下注的用户，其同一Africa/Lagos业务日全部成功充值、成功提现及冲提比；不是某笔资金对Tada游戏的直接归因。','daily':rows,'summary':summary,'quality':{'executed_via':'Google Cloud BigQuery API','segments':3,'duplicate_money_rows':0,'aggregate_only':True,'user_or_order_ids_returned':False,'tada_play_id_range':'9150001—9159999','mode_id':11,'robots_and_test_users_excluded':True},'boundary':'同一Tada参与用户可能同时玩其他游戏或提取历史余额；结果描述Tada参与人群的同日钱包表现，不证明Tada导致充值或提现。'}
(ROOT/'tada-tc-2026-09-10-vs-prior7.json').write_text(json.dumps(result,ensure_ascii=False,indent=2));print(json.dumps(summary,ensure_ascii=False))
