-- Run directly in MySQL by the DBA. Metabase connection is intentionally read-only.
-- Session time zone must remain Africa/Lagos.

CREATE TABLE IF NOT EXISTS whot_center.mart_lifecycle_v2_joint_daily_rawlog (
  business_date DATE NOT NULL,
  game_id INT NOT NULL,
  display_lifecycle INT NOT NULL,
  data_scope VARCHAR(16) NOT NULL,
  population_type VARCHAR(16) NOT NULL,
  row_scope VARCHAR(16) NOT NULL,
  game_name VARCHAR(64) NOT NULL,
  game_type VARCHAR(32) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  is_joint TINYINT(1) NOT NULL,
  is_self_developed TINYINT(1) NULL,
  app_version VARCHAR(64) NOT NULL,
  package_id VARCHAR(128) NOT NULL,
  distribution_channel_id VARCHAR(128) NOT NULL,
  attribution_media_id VARCHAR(128) NOT NULL,
  attribution_channel_id VARCHAR(128) NOT NULL,
  real_profit DECIMAL(24,4) NULL,
  expected_profit DECIMAL(24,4) NULL,
  adjusted_profit DECIMAL(24,4) NULL,
  entire_bet DECIMAL(24,4) NULL,
  bankruptcy_bet DECIMAL(24,4) NULL,
  bankruptcy_profit DECIMAL(24,4) NULL,
  control_bet DECIMAL(24,4) NULL,
  control_profit DECIMAL(24,4) NULL,
  expected_rtp_ratio DECIMAL(12,8) NULL,
  actual_profit DECIMAL(24,4) NULL,
  base_bet DECIMAL(24,4) NULL,
  base_actual_profit DECIMAL(24,4) NULL,
  entire_actual_rtp_ratio DECIMAL(12,8) NULL,
  base_actual_rtp_ratio DECIMAL(12,8) NULL,
  entire_expected_profit DECIMAL(24,4) NULL,
  base_expected_profit DECIMAL(24,4) NULL,
  recharge_count BIGINT NULL,
  recharge_amount DECIMAL(24,4) NULL,
  repeat_recharge_count BIGINT NULL,
  repeat_recharge_amount DECIMAL(24,4) NULL,
  withdraw_count BIGINT NULL,
  withdraw_amount DECIMAL(24,4) NULL,
  controlled_user_count BIGINT NULL,
  controlled_count BIGINT NULL,
  absolute_bankrupt_user_count BIGINT NULL,
  absolute_bankrupt_count BIGINT NULL,
  retention_user_count BIGINT NULL,
  upgrade_user_count BIGINT NULL,
  user_count BIGINT NULL,
  tc_ratio DECIMAL(12,8) NULL,
  flow_recharge_ratio DECIMAL(12,8) NULL,
  loss_coefficient DECIMAL(12,8) NULL,
  source_row_count INT NOT NULL,
  pool_type_coverage SMALLINT NOT NULL,
  data_cutoff_at DATETIME NOT NULL,
  data_status VARCHAR(32) NOT NULL,
  metric_version VARCHAR(64) NOT NULL,
  metric_limitations VARCHAR(512) NOT NULL,
  refreshed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (business_date, game_id, display_lifecycle),
  KEY idx_filter (business_date, row_scope, display_lifecycle, game_id),
  KEY idx_game (business_date, game_id, display_lifecycle)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Review execution plan and table lock policy with the DBA before applying.
-- This source index is absent in the observed metadata and is the recommended refresh index.
ALTER TABLE whot_center.stat_lifecycle_pool_v2_log
  ADD INDEX idx_lifecycle_refresh (change_type, data_type, time);
