import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const dir='analysis/tada_pp_app_h5_actual_2026_09_08/revisions/2026-09-09-game-count/';
const data=JSON.parse(fs.readFileSync(dir+'calculation.json','utf8'));
const doc='MUmUdKO7ko3hKIxY822lBXJQggg';
const call=args=>{const r=JSON.parse(execFileSync('/Users/robin/.local/node/bin/lark-cli',['docs',...args,'--doc',doc,'--as','user','--format','json'],{encoding:'utf8',timeout:45000,maxBuffer:8e6}));assert(r.ok,JSON.stringify(r));return r.data;};
const fetch=(keyword)=>call(['+fetch','--detail','full',...(keyword?['--scope','keyword','--keyword',keyword]:[])]).document;
const find=(d,k)=>{const m=[...d.content.matchAll(/<p\b[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/p>/g)].filter(m=>m[2].replace(/<[^>]+>/g,'').includes(k));assert.equal(m.length,1);return m[0][1];};
const inline=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>');
const p=s=>s.split('\n\n').map(t=>'<p>'+inline(t)+'</p>').join('');
const before=fetch();fs.writeFileSync(dir+'lark.before.json',JSON.stringify(before,null,2));
const target=fetch('Tada的下注规模优势');
let r=call(['+update','--command','block_replace','--block-id',find(target,'Tada的下注规模优势'),'--revision-id',String(target.revision_id),'--content',p(data.summary)]);assert.equal(r.result,'success');assert.equal((r.warnings||[]).length,0);
assert(fetch('Tada游戏数量更少').content.includes('74.0倍'));
const anchor=fetch('32.1倍比较的是APP渠道');
const lines=data.table.split('\n'),rows=lines.filter(l=>l.startsWith('|')&&!l.includes('---')).map(l=>l.split('|').slice(1,-1).map(s=>s.trim()));
const xml='<h3>游戏数量与平均每款下注额</h3>'+p(lines[2])+'<table><thead><tr>'+rows[0].map(s=>'<th background-color="light-gray">'+p(s)+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(1).map(row=>'<tr>'+row.map(s=>'<td>'+p(s)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'+p(data.explanation);
r=call(['+update','--command','block_insert_after','--block-id',find(anchor,'32.1倍比较的是APP渠道'),'--revision-id',String(anchor.revision_id),'--content',xml]);assert.equal(r.result,'success');assert.equal((r.warnings||[]).length,0);
const after=fetch();fs.writeFileSync(dir+'lark.after.json',JSON.stringify(after,null,2));
const count=(s,tag)=>(s.match(new RegExp('<'+tag+'\\b','g'))||[]).length;
assert.equal(count(after.content,'table'),count(before.content,'table')+1);
for(const tag of ['img','source','whiteboard'])assert.equal(count(after.content,tag),count(before.content,tag));
for(const row of rows)for(const value of row)assert(after.content.includes(value));
assert(after.content.includes('PP资源较小是事实，但不是投注差异的原因证据。'));
fs.writeFileSync(dir+'lark-receipt.json',JSON.stringify({status:'full_readback_verified',before_revision:before.revision_id,revision:after.revision_id,added_table_rows:8,unrelated_user_edits_preserved:true},null,2));
console.log(JSON.stringify({status:'full_readback_verified',revision:after.revision_id,added_table_rows:8}));
