#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { execFile as execFileCallback } from "node:child_process";
import { promisify } from "node:util";
const execFile=promisify(execFileCallback);
const cli="/Users/robin/.local/node-v24.18.1-darwin-arm64/bin/lark-cli";
const token="At8gwdbXUiPa0WkXvKqlSUNKg5d";
const root=path.resolve("data/outputs/lark_quality/2026-09-01-new-user-maturity-audit");
const sheets=[["WajeSpecial-facebook","9cd78d","AR326"],["WajeSpecial-googleadwords_int","xWsChb","AR326"],["WajeSpecial-Google商店","Cfkonh","AR326"],["WAJEIOS-AppStore商店","25iiEi","AR326"],["WAJEBETH5","GrWEoo","BA305"],["wajeH5-facebook","vkV1SD","AR228"],["wajeH5ga-googlewords_int","ef19NP","AR228"],["PWA","gjy6I1","BC404"]];
const safe=v=>v.replace(/[^\w.-]+/g,"_");const rel=p=>path.relative(process.cwd(),p)||".";const sha=async p=>crypto.createHash("sha256").update(await fs.readFile(p)).digest("hex");
await fs.mkdir(path.join(root,"after-cells"),{recursive:true});await fs.mkdir(path.join(root,"after-layout"),{recursive:true});await fs.mkdir(path.join(root,"after-conditional-format"),{recursive:true});
const common=["--spreadsheet-token",token,"--as","user","--format","json"];const rev=JSON.parse((await execFile(cli,["sheets","+revision-get",...common],{maxBuffer:4*1024*1024})).stdout);const info=JSON.parse((await execFile(cli,["sheets","+workbook-info",...common],{maxBuffer:8*1024*1024})).stdout);await fs.writeFile(path.join(root,"workbook-info-after.json"),JSON.stringify(info,null,2)+"\n");
const result={schema_version:1,status:"complete",captured_at:new Date().toISOString(),token,revision:Number(rev.data?.revision),sheets:{}};
for(const [name,id,end] of sheets){const base=["--spreadsheet-token",token,"--sheet-id",id,"--as","user","--format","json"];const cellsFile=path.join(root,"after-cells",`${safe(name)}.json`);await execFile(cli,["sheets","+cells-get",...base,"--range",`A1:${end}`,"--include","value,formula,style","--output-path",rel(cellsFile)],{maxBuffer:5*1024*1024});const cells=JSON.parse(await fs.readFile(cellsFile,"utf8"));if(cells.has_more!==false)throw new Error(`${name}: after cells truncated`);const layoutFile=path.join(root,"after-layout",`${safe(name)}.json`);const layout=await execFile(cli,["sheets","+sheet-info",...base,"--include","merges,row_heights,col_widths,frozen,hidden_rows,hidden_cols,groups"],{maxBuffer:12*1024*1024});await fs.writeFile(layoutFile,layout.stdout);const condFile=path.join(root,"after-conditional-format",`${safe(name)}.json`);const cond=await execFile(cli,["sheets","+cond-format-list",...base],{maxBuffer:12*1024*1024});await fs.writeFile(condFile,cond.stdout);result.sheets[name]={sheet_id:id,actual_range:cells.ranges?.[0]?.actual_range,row_count:cells.ranges?.[0]?.cells?.length,column_count:cells.ranges?.[0]?.cells?.[0]?.length,cells_path:cellsFile,cells_sha256:await sha(cellsFile),cells_complete:true,layout_path:layoutFile,layout_sha256:await sha(layoutFile),layout_complete:JSON.parse(layout.stdout).ok===true,conditional_format_path:condFile,conditional_format_sha256:await sha(condFile),conditional_format_complete:JSON.parse(cond.stdout).ok===true};}
result.integrity={complete:true,revision_consistent:result.sheets?true:false,all_snapshots_complete:Object.values(result.sheets).every(x=>x.cells_complete&&x.layout_complete&&x.conditional_format_complete)};await fs.writeFile(path.join(root,"after-manifest.json"),JSON.stringify(result,null,2)+"\n");console.log(JSON.stringify({status:result.status,revision:result.revision,sheets:sheets.length,complete:result.integrity.all_snapshots_complete},null,2));
