import fs from "node:fs/promises";
import path from "node:path";
import {FileBlob,SpreadsheetFile}from"@oai/artifact-tool";
const root=path.resolve("analysis/top30_tc_uidlog_2026_09_10"),file=path.resolve("outputs/019fc549-3241-7d52-90f5-0b39c2e03530/9月10日资产变动汇总_前30.xlsx");
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(file));
const summary=wb.worksheets.getItem("摘要"),notes=wb.worksheets.getItem("查询说明");
const before=await wb.inspect({kind:"table",range:"摘要!A9:I22",include:"values,formulas",tableMaxRows:20,tableMaxCols:12,maxChars:8000});
const beforeImage=await wb.render({sheetName:"摘要",autoCrop:"all",scale:1,format:"png"});await fs.writeFile(path.join(root,"preview-摘要-资产类型-before.png"),new Uint8Array(await beforeImage.arrayBuffer()));
const font="Arial",navy="#17324D",blue="#2F75B5",lightBlue="#DCEAF7",lightGray="#F3F6F8",line="#D7E0E7",red="#C0504D";
const labels={5001:"游戏币（Chip）",5002:"现金（Cash）",5006:"Waje游戏币（WajeChip）",5007:"Waje现金（WajeCash）"};
const aggregate=JSON.parse(await fs.readFile(path.join(root,"aggregate-result-final.json"),"utf8"));
const assets=aggregate.filter(r=>r.section==="资产").sort((a,b)=>a.asset_key.localeCompare(b.asset_key));
try{summary.unmergeCells("A9:H9");}catch{}summary.mergeCells("A9:I9");summary.getRange("A9").values=[["按资产ID汇总（不同资产单位不可相加）"]];summary.getRange("A9").format={fill:lightBlue,font:{name:font,size:11,bold:true,color:navy},verticalAlignment:"center"};
summary.getRange("A10:I14").clear({applyTo:"all"});
summary.getRange("A10:I10").values=[["资产ID","资产类型（中文）","覆盖用户","事件数","事件占比","流入","流出","净变动","净变动/总流量"]];
summary.getRange("A10:I10").format={fill:navy,font:{name:font,size:10,bold:true,color:"#FFFFFF"},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true,borders:{insideVertical:{style:"thin",color:"#FFFFFF"},bottom:{style:"thin",color:navy}}};
summary.getRange("A11:D14").values=assets.map(r=>{const id=Number(r.asset_key.replace("asset_id=",""));return[id,labels[id],r.user_count,r.event_count];});
summary.getRange("F11:H14").values=assets.map(r=>[r.inflow,r.outflow,r.net_change]);
for(let i=11;i<=14;i++){summary.getRange(`E${i}`).formulas=[[`=D${i}/$C$6`]];summary.getRange(`I${i}`).formulas=[[`=H${i}/(F${i}+G${i})`]];}
summary.getRange("A11:A14").format.numberFormat="0";summary.getRange("C11:D14").format.numberFormat="#,##0";summary.getRange("E11:E14").format.numberFormat="0.0%";summary.getRange("F11:H14").format.numberFormat="#,##0";summary.getRange("I11:I14").format.numberFormat="0.00%";summary.getRange("A11:I14").format.borders={bottom:{style:"thin",color:line}};summary.getRange("B11:B14").format.font={name:font,size:10,bold:true,color:navy};
summary.getRange("I11:I14").conditionalFormats.add("cellIs",{operator:"lessThan",formula:0,format:{fill:"#FDE9E7",font:{color:red,bold:true}}});summary.getRange("I11:I14").conditionalFormats.add("cellIs",{operator:"greaterThanOrEqual",formula:0,format:{fill:"#E2F0D9",font:{color:"#38761D",bold:true}}});
summary.getRange("A:A").format.columnWidth=11;summary.getRange("B:B").format.columnWidth=24;summary.getRange("C:I").format.columnWidth=14;
summary.getRange("K17:K20").formulas=[["=I11"],["=I12"],["=I13"],["=I14"]];
summary.getRange("A18").values=[["2. 现金（5002）占80.4%事件，游戏币（5001）占16.2%；另有60条事件来自不足10名用户的低覆盖资产，已合并抑制。"]];
summary.getRange("A21").values=[["5. 现金（5002）中，提现扣除9000002与提现手续费9000211均为380条；手续费变动量约为提现扣除的1.02%。"]];
summary.getRange("A22").values=[["6. PP下注9010400与PP cash返还9010403已映射。资产中文名称保留原始ID，便于与日志和字典对账。"]];
notes.getRange("A25:B25").values=[["资产类型解释","5001=游戏币（Chip）；5002=现金（Cash）；5006=Waje游戏币（WajeChip）；5007=Waje现金（WajeCash）"]];
notes.getRange("A26:B26").values=[["资产解释依据","根据9月10日充值／提现、Tada chip／cash返还的成对资产变化关系；保留原始ID用于核对"]];
notes.getRange("A25:A26").format.font={name:font,size:10,bold:true,color:navy};notes.getRange("A25:B26").format.borders={bottom:{style:"thin",color:line}};notes.getRange("B25:B26").format.wrapText=true;notes.getRange("B25:B26").format.rowHeight=28;
const after=await wb.inspect({kind:"table",range:"摘要!A9:I22",include:"values,formulas",tableMaxRows:20,tableMaxCols:12,maxChars:9000});
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:300},summary:"asset label integration error scan"});
const afterImage=await wb.render({sheetName:"摘要",autoCrop:"all",scale:1,format:"png"});await fs.writeFile(path.join(root,"preview-摘要-资产类型.png"),new Uint8Array(await afterImage.arrayBuffer()));
await fs.writeFile(path.join(root,"asset-label-integration-verification.json"),JSON.stringify({labels,before:before.ndjson,after:after.ndjson,errorScan:errors.ndjson,scope:"summary and query notes only"},null,2));
const out=await SpreadsheetFile.exportXlsx(wb);await out.save(file);console.log(JSON.stringify({file,labels,formulaErrors:errors.ndjson.includes("matched 0")?0:"check"}));
