import fs from "node:fs/promises";
import {FileBlob,SpreadsheetFile}from"@oai/artifact-tool";
const file="/Users/robin/Documents/wajetan_analyst/outputs/019fc549-3241-7d52-90f5-0b39c2e03530/9月10日资产变动汇总_前30.xlsx";
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(file));
const sheets=await wb.inspect({kind:"sheet",include:"id,name",maxChars:2000});
const summary=await wb.inspect({kind:"table",range:"摘要!A5:I22",include:"values,formulas",tableMaxRows:30,tableMaxCols:12,maxChars:9000});
const formulas=await wb.inspect({kind:"formula",sheetId:"摘要",range:"A1:I22",maxChars:4000,options:{maxResults:50}});
const codeTable=await wb.inspect({kind:"table",range:"共同变动代码!A5:L24",include:"values,formulas",tableMaxRows:30,tableMaxCols:14,maxChars:12000});
const dictionary=await wb.inspect({kind:"table",range:"资产变动字典!A5:K20",include:"values,formulas",tableMaxRows:20,tableMaxCols:12,maxChars:8000});
const drawings=await wb.inspect({kind:"drawing",maxChars:4000});
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:300},summary:"exported workbook formula error scan"});
const preview=await wb.render({sheetName:"摘要",autoCrop:"all",scale:1,format:"png"});await fs.writeFile("analysis/top30_tc_uidlog_2026_09_10/preview-导出复核.png",new Uint8Array(await preview.arrayBuffer()));
const codePreview=await wb.render({sheetName:"共同变动代码",autoCrop:"all",scale:1,format:"png"});await fs.writeFile("analysis/top30_tc_uidlog_2026_09_10/preview-代码复核.png",new Uint8Array(await codePreview.arrayBuffer()));
const report={file,sheets:sheets.ndjson,summary:summary.ndjson,formulas:formulas.ndjson,codeTable:codeTable.ndjson,dictionary:dictionary.ndjson,drawings:drawings.ndjson,errorScan:errors.ndjson};await fs.writeFile("analysis/top30_tc_uidlog_2026_09_10/output-verification.json",JSON.stringify(report,null,2));
if(!sheets.ndjson.includes("摘要")||!sheets.ndjson.includes("查询说明")||!sheets.ndjson.includes("资产变动字典")||!drawings.ndjson.includes("chart"))throw new Error("Exported workbook structure incomplete");
if(!codeTable.ndjson.includes("Bets-Tada")||!codeTable.ndjson.includes("Withdraw-Fee")||!dictionary.ndjson.includes("AssetChangeTypeRecharge"))throw new Error("Dictionary formulas or source sheet did not survive export");
if(!summary.ndjson.includes("游戏币（Chip）")||!summary.ndjson.includes("Waje现金（WajeCash）"))throw new Error("Chinese asset labels did not survive export");
if(!errors.ndjson.includes("matched 0"))throw new Error("Formula errors found");
console.log(JSON.stringify({status:"verified",file,sheets:6,charts:3,dictionaryRows:283,formulaErrors:0}));
