import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url)),base=path.resolve(dir,'../..'),a=JSON.parse(fs.readFileSync(path.join(base,'artifact.json')));
const t=a.manifest.tables.find(t=>t.id==='return-common'),rows=a.snapshot.datasets[t.dataset],num=s=>Number(String(s).replace(/[,%]/g,''));
const max=t.columns.map((c,i)=>i>=2?Math.max(...rows.map(r=>num(r[c.field]))):null);
const body='### '+t.title+'\n\nTada浅蓝、PP浅橙；浅黄加粗标出每个观察日列的最高回访率，成熟样本数不参与峰值比较。\n\n| '+t.columns.map(c=>c.label).join(' | ')+' |\n| '+t.columns.map(()=> '---').join(' | ')+' |\n'+rows.map(r=>'| '+t.columns.map((c,i)=>i>=2&&num(r[c.field])===max[i]?'**'+r[c.field]+'**':r[c.field]).join(' | ')+' |').join('\n');
const age=a.manifest.blocks.find(b=>b.id==='return-age');const oldTable=age.body.split('\n\n').find(p=>p.startsWith('| 厂商 | 人群 | 渠道 |'));assert(oldTable);const data=oldTable.split('\n').slice(2).map(l=>l.split('|').slice(1,-1).map(s=>s.trim()));const peak={};for(const group of new Set(data.map(r=>r[1])))peak[group]=[4,5,6].map(i=>Math.max(...data.filter(r=>r[1]===group).map(r=>num(r[i]))));
const newTable=oldTable.split('\n').slice(0,2).join('\n')+'\n'+data.map(r=>'| '+r.map((v,i)=>i>=4&&num(v)===peak[r[1]][i-4]?'**'+v+'**':v).join(' | ')+' |').join('\n');
const legend='新用户浅蓝、老用户浅紫；厂商列Tada浅蓝、PP浅橙。浅黄加粗为同一新老分组内各观察日的最高回访率，起点人数不参与峰值比较。';
let patch='*** Begin Patch\n';
const file=path.join(base,'artifact.json'),old=fs.readFileSync(file,'utf8');fs.copyFileSync(file,path.join(dir,'artifact.before.json'));let next=old;
const c=a.manifest.charts.find(c=>c.id==='return-chart'),nc={...c,labels:{values:'all'},valueFormat:'number',unit:'%'};next=next.replace(JSON.stringify(c,null,2).split('\n').map(l=>'      '+l).join('\n'),JSON.stringify(nc,null,2).split('\n').map(l=>'      '+l).join('\n'));
const b=a.manifest.blocks.find(b=>b.id==='return-common-block'),nb={id:b.id,type:'markdown',body,sourceId:'src-return'};next=next.replace(JSON.stringify(b,null,2).split('\n').map(l=>'      '+l).join('\n'),JSON.stringify(nb,null,2).split('\n').map(l=>'      '+l).join('\n'));
next=next.replace(JSON.stringify(age.body),JSON.stringify(age.body.replace(oldTable,legend+'\n\n'+newTable)));assert(next!==old);fs.writeFileSync(path.join(dir,'artifact.candidate.json'),next);
let md=fs.readFileSync(path.join(base,'报告.md'),'utf8');fs.copyFileSync(path.join(base,'报告.md'),path.join(dir,'报告.before.md'));const start=md.indexOf('### '+t.title),tail='| '+t.columns.map(c=>rows.at(-1)[c.field]).join(' | ')+' |',end=md.indexOf(tail,start)+tail.length;assert(start>=0&&end>start);md=md.slice(0,start)+body+md.slice(end);md=md.replace(oldTable,legend+'\n\n'+newTable);fs.writeFileSync(path.join(dir,'md.candidate'),md);
let py=fs.readFileSync(path.join(base,'build_report.py'),'utf8');fs.copyFileSync(path.join(base,'build_report.py'),path.join(dir,'build_report.before.py'));const tableLine=py.split('\n').find(l=>l.startsWith("table('return-common'"));py=py.replace(tableLine,tableLine+'\n'+"M['blocks'][-1] = "+JSON.stringify(nb));const chartLine=py.split('\n').find(l=>l.startsWith("chart('return-chart'"));py=py.replace(chartLine,chartLine+'\n'+"M['charts'][-1].update(labels={'values':'all'}, valueFormat='number', unit='%')");py=py.replace(oldTable,legend+'\n\n'+newTable);fs.writeFileSync(path.join(dir,'py.candidate'),py);
fs.writeFileSync(path.join(dir,'data.json'),JSON.stringify({body,legend,peak,max,chart_id:'return-chart',expected_label_count:20},null,2));console.log('Prepared');
